---
title: "2015 Water Use release metrics"
date: "July 31, 2018"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(googleAnalyticsR)
library(googleAuthR)
library(dplyr)
library(ggplot2)
library(lubridate)
```

```{r not_with_dims, echo = FALSE, message = FALSE, fig.width=8, fig.height=3 }
view <- "177200146"
release_date <- as.Date("2018-06-19")
gar_auth_service('~/.vizlab/VIZLAB-a48f4107248c.json')

source('bulk_sessions.R')
sessions_sources <- get_time_series_plot(view, release_date) %>% group_by(big_source) %>% 
  summarize(n=sum(sessions))
#ggplot(sessions_sources, aes(x = reorder(big_source, desc(n)), y = n)) + geom_col() +
#  ylab("Visits") + xlab("Source")




total_sessions <- invisible(google_analytics(viewId = view, 
                                             date_range = c(start = release_date, end = Sys.Date()),
                                             metrics = "sessions")$sessions)



```

## Overall views
The gif and static map, which could be fully shared over social media, had a much wider reach than the data viz or report:

```{r overall, echo = FALSE, fig.height=2.5}
df <- tibble(thing = c("Report", "Data viz", "GIFs", "Static images"),
             views = c(1514,3132, 198658,76315))
ggplot(df, aes(x = reorder(thing, desc(views)), y = views)) + geom_col() +
  xlab("Product") + ylab("Views")
ggsave("overall_views.png")
```


## User engagement
Nearly half of all visits viewed the entire viz:

```{r new_dims, fig.align='center', echo = FALSE, message=FALSE, warning = FALSE, fig.height=3.5}
events <- google_analytics(viewId = view, 
                           date_range = c(start = release_date, end = Sys.Date()),
                           dimensions = c("eventAction", "eventLabel", "dimension2"),
                           metrics = c("totalEvents"), max = -1, 
                           anti_sample = TRUE) %>% rename(sessionID = dimension2)
scrolls <- events %>% filter(eventAction == "scroll") %>% group_by(eventLabel) %>% 
  summarize(n=length(unique(sessionID))) %>% arrange(desc(n)) %>% 
  mutate(fraction_of_sessions = round(n/total_sessions, digits = 2),
         eventLabel = gsub(pattern = "-", replacement = " ", eventLabel)) 

state_game_events <- events %>% filter(grepl(pattern = "state", x= eventAction)) 
game_event_ids <- unique(state_game_events$sessionID)
state_df <- tibble(eventLabel = "attempted interactive game",
                       fraction_of_sessions = round(length(game_event_ids)/total_sessions, digits = 2))

#changed category
cat_changes <- events %>% filter(grepl(pattern = "update category", 
                                       x=eventAction))
cat_change_ids <- unique(cat_changes$sessionID)
cat_change_df <- tibble(eventLabel = "changed WU category",
                        fraction_of_sessions = round(length(cat_change_ids)/total_sessions, digits = 2))
library(tidyr)
state_zooms <- events %>% filter(grepl(pattern = "update view", x = eventAction)) %>% separate(col = "eventLabel", into = c("newView", "oldView", "category"), sep = ";") %>% mutate(newView=trimws(gsub("newView=", "", newView)),
       oldView = trimws(gsub("oldView=", "", oldView))) %>% filter(newView != oldView) 
zoom_change_ids <- unique(state_zooms$sessionID) 
zoom_change_df <- tibble(eventLabel = "zoomed to/from state view",
                         fraction_of_sessions = round(length(zoom_change_ids)/total_sessions, digits = 2))
                                                                                                                                                                                     
scrolls_state <- bind_rows(scrolls, state_df, cat_change_df, zoom_change_df) %>% 
  filter(!eventLabel %in% c("scrolled to national pie", "scrolled to rank states interactive", "scrolled to data collection", "scrolled to related items")) %>% 
  mutate(eventLabel = gsub("scrolled to national static pie", "viewed national annotated map", eventLabel),
         eventLabel = gsub("scrolled to", "viewed", eventLabel))

ggplot(scrolls_state, aes(x = reorder(eventLabel, desc(fraction_of_sessions)), y = fraction_of_sessions*100)) + geom_col() + theme(axis.text.x = element_text(angle = 45, hjust=1)) + xlab("User interactions") + ylab("Percent of visits") 
ggsave(filename = "engagement.png")
```







```{r platforms, echo = FALSE, message = FALSE, fig.height=3}

platforms <- invisible(get_platform_plot(view, release_date))
#platforms + ylab("Visits")
```

